### ISSUE TITLE
How to get the onion address after connecting to tor

### ISSUE THREAD

**Issue by be-thomas** [utopicnarwhal/utopic_tor_onion_proxy#1]
I want to get the onion address after connecting to tor.

Also, any possibility for iOS support?
Btw, thanks, for building this.

**Comment by utopicnarwhal** [comment]
It's the hardest thing to do. To use Tor Onion Proxy we should to send our requests through SOCKS4a proxy that Tor starts on random port. I've created the issue about it https://github.com/dart-lang/sdk/issues/42920
So I've modified dart http client implementation for my project so it can use socks4a proxies. You can check this out here:
https://github.com/utopicnarwhal/flibusta-mobile/blob/master/lib/services/http_client/dio_http_client_adapters/my_http_impl.dart
I didn't have an iOS device when I wrote this, now I have but I'm too busy. Furthermore, I don't know how to use Swift and it's libraries at all.

I'm glad when somebody use my package.
